server:
  forward-headers-strategy: framework
spring:
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

  data:
    redis:
      host: ${SPRING_REDIS_HOST:localhost}
      port: ${SPRING_REDIS_PORT:6379}
      password: ${SPRING_REDIS_PASSWORD:}
      lettuce:
        pool:
          max-active: 8
          max-idle: 8
          min-idle: 2

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            scope:
              - email
              - profile
            redirect-uri: ${GOOGLE_REDIRECT_URI}

  task:
    scheduling:
      enabled: true

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: debug
supabase:
  url: ${SUPABASE_URL}

payment:
  sepay:
        webhook-token: ${SEPAY_WEBHOOK_TOKEN}
        bank-bin: ${SEPAY_BANK_BIN}
        account-number: ${SEPAY_ACCOUNT_NUMBER}
        account-name: ${SEPAY_ACCOUNT_NAME}

app:
  jwt:
    secret: ${JWT_SECRET}
    expiration-seconds: ${JWT_EXPIRATION_SECONDS:3600}
  frontend-url: ${FRONTEND_URL}
  api-url: ${API_URL}
  cors:
    allowed-origins: ${CORS_ALLOWED_ORIGINS}

