spring:
  datasource:
    url: jdbc:postgresql://toeic-baotran24092004-0bec.h.aivencloud.com:17496/toeic?sslmode=require
    username: avnadmin
    password: AVNS_6dpk6bbQdxxJVLlR717
    hikari:
      maximum-pool-size: 5
      minimum-idle: 1

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true

  flyway:
    enabled: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 261892871681-pf7dj933v8jjat676lp8snl0ahgfjfmg.apps.googleusercontent.com
            client-secret: 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
            scope:
              - email
              - profile

logging:
  level:
    org.hibernate.SQL: debug
    org.springframework.security: debug
